language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23
jdk:
  - oraclejdk8

script:
  ./gradlew test connectedCheck

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.gradle
